packer {
  required_version = ">=1.7.0"
  required_plugins {
    docker = {
      source  = "github.com/hashicorp/docker"
      version = ">=0.0.7"
    }
  }
}

source "docker" "autogenerated_1" {
  discard = true
  image   = "ubuntu:latest"
}

build {
  description = "Converge Example"
  sources     = ["source.docker.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "apt-get update",
      "apt-get -qq -y install wget",
      "wget -p /tmp/ -O install-converge.sh https://raw.githubusercontent.com/asteris-llc/converge/master/install-converge.sh",
      "chmod a+x /tmp/install-converge.sh",
      "./tmp/install-converge.sh"
    ]
  }

  provisioner "converge" {
    module = "https://raw.githubusercontent.com/asteris-llc/converge/master/samples/fileContent.hcl"
    params = {
      message = "Hello, Packer!"
    }
  }
}
